### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by drewlobel** [alniles/emulatorjs#2]
So I was trying to make it than I got a network error message. 

https://alniles.github.io/emulatorjs/play.html?id=1634149214773372572320577224&core=gba&data=1f7Ig7Sq3WwHh1snD_XLE3PcLVL1Yt_WX&button=Start%20Game&img=0&name=pokemon%20emerald&iurl=false

**Comment by alniles** [comment]
How long did you wait?

**Comment by alniles** [comment]
Try it unziped.

**Comment by alniles** [comment]
Send a screen shot of the blocked page.

**Comment by alniles** [comment]
what about this: http://www.allancoding.ml/app/emulatorjs/download.php

**Comment by drewlobel** [comment]
That's fine. Makes sense.

**Comment by drewlobel** [comment]
How would you do it?

**Comment by alniles** [comment]
Using github :)

**Comment by drewlobel** [comment]
Could you? Like would there be a guide for me or something?

**Comment by alniles** [comment]
Coding. What did you think.

**Comment by drewlobel** [comment]
No crap. Is there a guide for me to do that?

**Comment by alniles** [comment]
No it is really hard to do. But I am willing to do a lot of them. Just make a new issue when it done not work.

**Comment by drewlobel** [comment]
Ok. Ill keep that in mind.
